import Head from "next/head";
import React from "react";
import Documentaries from "../../../components/resources/documentaries/Documentaries";
import Header from "../../../components/resources/documentaries/Header";

export default function documentary() {
  return (
    <div>
      <Head>
        <title>Learn from documentary | Gurukul DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Documentaries/>
    </div>
  );
}
