import Head from "next/head";
import React from "react";
import ConsensusAlgorithm from "../../../components/resources/consensus/Consensus";
import ConsensusHeader from "../../../components/resources/consensus/Header";

export default function Consensus() {
  return (
    <div>
      <Head>
        <title>Consensus Algorithms | Gurukul DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ConsensusHeader />
      <ConsensusAlgorithm/>
    </div>
  );
}
