import Head from "next/head";
import React from "react";
import Bounties from "../../components/earn/Bounties";
import BountiesHeader from "../../components/earn/BountiesHeader";

export default function BountiesPage() {
  return (
    <div>
      <Head>
        <title>Bounties | BlockShala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BountiesHeader/>
      <Bounties/>
    </div>
  );
}
