import Head from "next/head";
import React from "react";
import EarnHeader from "../../components/earn/Header";
import Jobs from "../../components/earn/Jobs";
import Jobs2 from "../../components/earn/Jobs2";

function earn() {
  return (
    <div>
      <Head>
        <title>Learn | BlockShala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <EarnHeader />
      {/* <Jobs2/> */}
    </div>
  );
}

export default earn;
