import Head from "next/head";
import React from "react";
import Jobs from "../../components/earn/Jobs";
import JobsHeader from "../../components/earn/JobsHeader";

export default function JobPage() {
  return (
    <div>
      <Head>
        <title>Jobs | BlockShala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <JobsHeader/>
      <Jobs/>
    </div>
  );
}
