import Head from "next/head";
import React from "react";
import BuildHeader from "../components/build/Header";

function build() {
  return (
    <div>
      <Head>
        <title>Learn | BlockShala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BuildHeader />
    </div>
  );
}

export default build;
