import Head from "next/head";
import React from "react";
import EarnHeader from "../components/earn/Header";

function earn() {
  return (
    <div>
      <Head>
        <title>Learn | BlockShala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <EarnHeader />
    </div>
  );
}

export default earn;
