import Head from "next/head";
import React from "react";
import LearnHeader from "../components/learn/Header";
import LearnTech from "../components/learn/Tech";

export default function Glossary() {
  return (
    <div>
      <Head>
        <title>Learn | BlockShala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LearnHeader />
      <LearnTech />
    </div>
  );
}
