import Head from "next/head";
import React from "react";
import ChallengesList from "../../components/challenges/Challenges";
import ChallengesHeader from "../../components/challenges/Header";

export default function Challenges() {
  return (
    <div>
      <Head>
        <title>Learn | BlockShala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ChallengesHeader />
      <ChallengesList />
    </div>
  );
}
