import Head from "next/head";
import React from "react";
import Header from "../../components/layout/Header";

export default function Resources() {
  return (
    <div>
      <Head>
        <title>WEB3 Resourses | Gurukul DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        title="Resources"
        emoji={"🌱"}
        description="curated list of web3 resources"
        headerBgColor={"#E8EBFF"}
      />
    </div>
  );
}
